{% set name = "trame-common" %}
{% set version = "1.2.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/trame_common-{{ version }}.tar.gz
  sha256: e31f963436f70a9162b3777ece311f1969580f6ac79a6cc860b97fa33ed4c05b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - trame_common
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Kitware/trame-common
  summary: Dependency less classes and functions for trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
