{% set name = "trame-common" %}
{% set version = "1.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/trame_common-{{ version }}.tar.gz
  sha256: 3dcec7a0fa32ed217ede05c83f03f1013e84bc36e8e6ff92cf828077df6994fa

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - trame_common
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/Kitware/trame-common
  summary: Dependency less classes and functions for trame
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jourdain
